export interface Product {
  slug: string
  name: string
  modelNumber: string
  tagline: string
  description: string
  shortDescription: string
  category: 'fabricated-channel-letters' | 'cast-block-acrylic' | 'cabinet-signs'
  isBestSeller?: boolean
  isQuickShip?: boolean
  image: string
  gallery: string[]
  specs: {
    label: string
    value: string
  }[]
  applications: string[]
  features: string[]
  relatedSlugs: string[]
}

export const products: Product[] = [
  // ──────────────────────────────────────────
  // FABRICATED CHANNEL LETTERS
  // ──────────────────────────────────────────
  {
    slug: 'edgeluxe-lp1',
    name: 'Flat Cutout Letters (FCO)',
    modelNumber: 'EdgeLuxe LP1',
    tagline: 'Premium non-illuminated dimensional letters in any material.',
    description: 'Non-illuminated flat cut-out letters in premium materials including wood, aluminum, stainless steel, and acrylic. Precision CNC or laser cut from solid material for clean, dimensional letterforms. An excellent choice for interior branding, wayfinding, and projects where a refined non-illuminated presence is preferred.',
    shortDescription: 'Non-illuminated flat cut-out letters in premium materials including wood, aluminum, stainless steel, and acrylic.',
    category: 'fabricated-channel-letters',
    isQuickShip: true,
    image: '/images/hero-lp1.jpg',
    gallery: [
      '/images/hero-lp1.jpg',
      '/images/products/lp1-day.jpg',
      '/images/products/lp1-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: 'Wood, aluminum, stainless steel, acrylic and more' },
      { label: 'Thickness', value: '1mm (0.039") to 200mm (7.87")' },
      { label: 'Customization', value: 'Broad range of acrylic colors, paint, and vinyl' },
      { label: 'Min. Stroke Width', value: '5mm (0.2")' },
      { label: 'Min. Height', value: '10mm (0.4")' },
      { label: 'Maintenance', value: 'No maintenance required' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Interior lobby and reception areas',
      'Wayfinding and directional signage',
      'Corporate branding',
      'Architectural accent features',
    ],
    features: [
      'Premium materials \u2014 wood, aluminum, stainless steel, acrylic',
      'Thickness from 1mm to 200mm',
      'Custom colors and finishes',
      'Precision CNC or laser cut',
      'No maintenance required',
      'Indoor and outdoor rated',
    ],
    relatedSlugs: ['edgeluxe-lp5', 'edgeluxe-lp31', 'edgeluxe-lp11-f'],
  },
  {
    slug: 'edgeluxe-lp31',
    name: 'Halo-Lit Standoff Mount',
    modelNumber: 'EdgeLuxe LP3.1',
    tagline: 'Dramatic backlit glow with elegant standoff mounting.',
    description: 'Fabricated stainless steel letters with halo illumination from the back using standoff spacers for elegant wall lighting effects. The standoff mount holds letters away from the wall surface, allowing LED light to wash evenly behind the letterform for maximum visual impact.',
    shortDescription: 'Fabricated stainless steel letters with halo illumination from the back using standoff spacers for elegant wall lighting effects.',
    category: 'fabricated-channel-letters',
    image: '/images/hero-lp31.jpg',
    gallery: [
      '/images/hero-lp31.jpg',
      '/images/products/lp31-day.jpg',
      '/images/products/lp31-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: 'Fabricated stainless steel' },
      { label: 'Illumination', value: 'Halo-lit with standoff spacers' },
      { label: 'Available Depths', value: '30mm (1.2"), 50mm (2"), 80mm (3.1"), 100mm (3.9")' },
      { label: 'Customization', value: 'Any PMS color, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Stroke Width', value: '15mm (0.6")' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'Serviceable LEDs' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Upscale retail and boutique storefronts',
      'Hotels and hospitality',
      'Corporate headquarters',
      'Architectural feature signage',
    ],
    features: [
      'Halo illumination with standoff spacers',
      'Depth options from 30mm to 100mm',
      'PMS color matching available',
      'Serviceable LEDs for easy maintenance',
      'UL listed components throughout',
      'Colorful halo effects with translucent acrylics',
    ],
    relatedSlugs: ['edgeluxe-lp32', 'edgeluxe-lp5', 'edgeluxe-lp11-b'],
  },
  {
    slug: 'edgeluxe-lp32',
    name: 'Halo-Lit Flush Mount',
    modelNumber: 'EdgeLuxe LP3.2',
    tagline: 'Sleek flush-mounted halo illumination for architectural applications.',
    description: 'Fabricated stainless steel flush-mounted letters with partial side-lit halo effect for sleek architectural applications. The flush-mount design sits directly against the mounting surface while LEDs create a refined halo glow through a narrow channel.',
    shortDescription: 'Fabricated stainless steel flush-mounted letters with partial side-lit halo effect for sleek architectural applications.',
    category: 'fabricated-channel-letters',
    image: '/images/hero-lp32.jpg',
    gallery: [
      '/images/hero-lp32.jpg',
      '/images/products/lp32-day.jpg',
      '/images/products/lp32-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: 'Fabricated stainless steel' },
      { label: 'Illumination', value: 'Partial side-lit halo, flush mount' },
      { label: 'Available Depths', value: '30mm (1.2"), 50mm (2"), 80mm (3.1"), 100mm (3.9")' },
      { label: 'Customization', value: 'Any PMS color, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Stroke Width', value: '15mm (0.6")' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'Serviceable LEDs' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Properties with restricted projection requirements',
      'Interior corporate signage',
      'Medical and professional offices',
      'Clean, architectural storefronts',
    ],
    features: [
      'Partial side-lit halo flush-mount design',
      'Depth options from 30mm to 100mm',
      'PMS color matching available',
      'No visible standoff hardware',
      'UL listed LEDs and power supplies',
      'Colorful halo effects with translucent acrylics',
    ],
    relatedSlugs: ['edgeluxe-lp31', 'edgeluxe-lp5', 'edgeluxe-lp11-bs'],
  },
  {
    slug: 'edgeluxe-lp5',
    name: 'Trimless Face-Lit Channel Letters',
    modelNumber: 'EdgeLuxe LP5',
    tagline: 'The clean, modern channel letter \u2014 no trim cap, no compromise.',
    description: 'Premium trimless fabricated stainless steel channel letters with step-router acrylic face for a clean, modern aesthetic. Our flagship product eliminates the visible trim cap found on traditional channel letters. The result is a seamless, flush face that delivers a premium look. German-engineered for precision fit and long-term durability.',
    shortDescription: 'Premium trimless fabricated stainless steel channel letters with step-router acrylic face for a clean, modern aesthetic.',
    category: 'fabricated-channel-letters',
    isBestSeller: true,
    image: '/images/hero-lp5.jpg',
    gallery: [
      '/images/hero-lp5.jpg',
      '/images/products/lp5-day.jpg',
      '/images/products/lp5-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: 'Thick gauge stainless steel returns, step-router acrylic face' },
      { label: 'Illumination', value: 'Face-lit, trimless design' },
      { label: 'Available Depths', value: '30mm (1.2"), 50mm (2"), 80mm (3.1"), 100mm (3.9")' },
      { label: 'Customization', value: 'Any PMS color, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Stroke Width', value: '15mm (0.6")' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'Serviceable LEDs' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Retail storefronts and shopping centers',
      'Restaurants and hospitality',
      'Corporate offices and medical facilities',
      'Multi-tenant building signage',
    ],
    features: [
      'Trimless design \u2014 no visible edges',
      'Face-lit illumination with step-router acrylic',
      'Thick gauge stainless steel construction',
      'Depth options from 30mm to 100mm',
      'PMS color matching available',
      'Serviceable LEDs for easy maintenance',
    ],
    relatedSlugs: ['edgeluxe-lp31', 'edgeluxe-lp11-f', 'edgeluxe-lp11-fb'],
  },

  // ──────────────────────────────────────────
  // CAST BLOCK ACRYLIC LETTERS
  // ──────────────────────────────────────────
  {
    slug: 'edgeluxe-lp11-f',
    name: 'Face-Lit Acrylic',
    modelNumber: 'EdgeLuxe LP11-F',
    tagline: 'Uniform face lighting with IP67 waterproof cast acrylic.',
    description: '30mm cast block acrylic with embedded LEDs for uniform face lighting. IP67 waterproof, maintenance-free design. Epoxy-sealed for heat dissipation and long-term durability in any weather condition.',
    shortDescription: '30mm cast block acrylic with embedded LEDs for uniform face lighting. IP67 waterproof, maintenance-free design.',
    category: 'cast-block-acrylic',
    image: '/images/hero-lp11-f.jpg',
    gallery: [
      '/images/hero-lp11-f.jpg',
      '/images/products/lp11-f-day.jpg',
      '/images/products/lp11-f-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: '30mm (1.2") cast block acrylic' },
      { label: 'Illumination', value: 'Embedded LEDs, uniform face-lit' },
      { label: 'Sealing', value: 'Epoxy-sealed IP67 waterproof' },
      { label: 'Customization', value: 'PMS colors, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Stroke Width', value: '12mm (0.47")' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'No maintenance required' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Interior lobby and reception signage',
      'Retail environments',
      'Medical and dental offices',
      'Boutique and luxury retail',
    ],
    features: [
      'Embedded LEDs for uniform face lighting',
      '30mm cast block acrylic construction',
      'IP67 waterproof epoxy sealed',
      'High water and dust-proof design',
      'No maintenance required',
      'PMS color matching available',
    ],
    relatedSlugs: ['edgeluxe-lp11-b', 'edgeluxe-lp11-fb', 'edgeluxe-lp5'],
  },
  {
    slug: 'edgeluxe-lp11-b',
    name: 'Back-Lit (Halo) Acrylic',
    modelNumber: 'EdgeLuxe LP11-B',
    tagline: 'Cast acrylic with a beautiful halo-lit backglow.',
    description: 'Cast block acrylic with embedded LEDs for uniform halo-lit effect using standoff spacers. Available in 15mm, 20mm, or 30mm depths. Epoxy-sealed for IP67 waterproofing and heat dissipation.',
    shortDescription: 'Cast block acrylic with embedded LEDs for uniform halo-lit effect using standoff spacers.',
    category: 'cast-block-acrylic',
    image: '/images/hero-lp11-b.jpg',
    gallery: [
      '/images/hero-lp11-b.jpg',
      '/images/products/lp11-b-day.jpg',
      '/images/products/lp11-b-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: '15mm, 20mm, or 30mm cast block acrylic' },
      { label: 'Illumination', value: 'Embedded LEDs, halo-lit with standoffs' },
      { label: 'Sealing', value: 'Epoxy-sealed IP67 waterproof' },
      { label: 'Customization', value: 'PMS colors, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Stroke Width', value: '12mm (0.47")' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'No maintenance required' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Upscale corporate lobbies',
      'Hotel and resort signage',
      'Premium retail environments',
      'Architectural feature installations',
    ],
    features: [
      'Halo illumination with standoff spacers',
      'Available in 15mm, 20mm, or 30mm depths',
      'IP67 waterproof epoxy sealed',
      'High water and dust-proof design',
      'No maintenance required',
      'PMS color matching available',
    ],
    relatedSlugs: ['edgeluxe-lp11-f', 'edgeluxe-lp11-fb', 'edgeluxe-lp11-bs'],
  },
  {
    slug: 'edgeluxe-lp11-fb',
    name: 'Face & Halo Combo',
    modelNumber: 'EdgeLuxe LP11-FB',
    tagline: 'The ultimate visibility solution \u2014 face and halo combined.',
    description: '30mm cast block acrylic with embedded LEDs for both face and halo illumination \u2014 the ultimate visibility solution. Maximum impact signage that delivers front-face illumination and a rear halo glow simultaneously.',
    shortDescription: '30mm cast block acrylic with embedded LEDs for both face and halo illumination \u2014 the ultimate visibility solution.',
    category: 'cast-block-acrylic',
    image: '/images/hero-lp11-fb.jpg',
    gallery: [
      '/images/hero-lp11-fb.jpg',
      '/images/products/lp11-fb-day.jpg',
      '/images/products/lp11-fb-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: '30mm (1.2") cast block acrylic' },
      { label: 'Illumination', value: 'Face + Halo combination lighting' },
      { label: 'Sealing', value: 'Epoxy-sealed IP67 waterproof' },
      { label: 'Customization', value: 'PMS colors, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Stroke Width', value: '12mm (0.47")' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'No maintenance required' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'High-visibility retail locations',
      'Entertainment and nightlife venues',
      'Restaurants and bars',
      'Any project where maximum impact is the goal',
    ],
    features: [
      'Face + Halo combination lighting',
      '30mm cast block acrylic construction',
      'IP67 waterproof epoxy sealed',
      'Maximum visibility day and night',
      'No maintenance required',
      'PMS color matching available',
    ],
    relatedSlugs: ['edgeluxe-lp11-f', 'edgeluxe-lp11-b', 'edgeluxe-lp5'],
  },
  {
    slug: 'edgeluxe-lp11-bs',
    name: 'Back & Side-Lit',
    modelNumber: 'EdgeLuxe LP11-BS',
    tagline: 'Subtle flush-mount illumination with elegant side glow.',
    description: '30mm cast block acrylic with partial back side-lit effect for flush-mount installations with subtle illumination. Creates an elegant side glow effect that adds dimension without overpowering the letterform.',
    shortDescription: '30mm cast block acrylic with partial back side-lit effect for flush-mount installations with subtle illumination.',
    category: 'cast-block-acrylic',
    image: '/images/hero-lp11-bs.jpg',
    gallery: [
      '/images/hero-lp11-bs.jpg',
      '/images/products/lp11-bs-day.jpg',
      '/images/products/lp11-bs-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: '30mm (1.2") cast block acrylic' },
      { label: 'Illumination', value: 'Back & Side-Lit, flush mount' },
      { label: 'Sealing', value: 'Epoxy-sealed IP67 waterproof' },
      { label: 'Customization', value: 'PMS colors, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Stroke Width', value: '12mm (0.47")' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'No maintenance required' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Properties with restricted projection requirements',
      'Interior corporate signage',
      'Clean, architectural storefronts',
      'Boutique environments',
    ],
    features: [
      'Partial back side-lit flush-mount design',
      '30mm cast block acrylic construction',
      'IP67 waterproof epoxy sealed',
      'Elegant side glow effect',
      'No maintenance required',
      'PMS color matching available',
    ],
    relatedSlugs: ['edgeluxe-lp11-fs', 'edgeluxe-lp11-s', 'edgeluxe-lp32'],
  },
  {
    slug: 'edgeluxe-lp11-fs',
    name: 'Front & Side-Lit',
    modelNumber: 'EdgeLuxe LP11-FS',
    tagline: 'Contemporary flush-mount with modern edge lighting.',
    description: '30mm cast block acrylic with partial front side-lit effect for contemporary flush-mount applications. Modern edge lighting creates a distinctive look that stands out in any setting.',
    shortDescription: '30mm cast block acrylic with partial front side-lit effect for contemporary flush-mount applications.',
    category: 'cast-block-acrylic',
    image: '/images/hero-lp11-fs.jpg',
    gallery: [
      '/images/hero-lp11-fs.jpg',
      '/images/products/lp11-fs-day.jpg',
      '/images/products/lp11-fs-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: '30mm (1.2") cast block acrylic' },
      { label: 'Illumination', value: 'Front & Side-Lit, flush mount' },
      { label: 'Sealing', value: 'Epoxy-sealed IP67 waterproof' },
      { label: 'Customization', value: 'PMS colors, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Stroke Width', value: '12mm (0.47")' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'No maintenance required' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Contemporary retail storefronts',
      'Modern office buildings',
      'Hospitality signage',
      'Architectural feature installations',
    ],
    features: [
      'Partial front side-lit flush-mount design',
      '30mm cast block acrylic construction',
      'IP67 waterproof epoxy sealed',
      'Modern edge lighting effects',
      'No maintenance required',
      'PMS color matching available',
    ],
    relatedSlugs: ['edgeluxe-lp11-bs', 'edgeluxe-lp11-s', 'edgeluxe-lp11-f'],
  },
  {
    slug: 'edgeluxe-lp11-s',
    name: 'Full Side-Lit',
    modelNumber: 'EdgeLuxe LP11-S',
    tagline: 'Dramatic edge-to-edge glow for standout signage.',
    description: '30mm cast block acrylic with full side-lit illumination for dramatic edge-to-edge glow effects. Creates a distinctive illuminated edge that makes letterforms glow from all sides.',
    shortDescription: '30mm cast block acrylic with full side-lit illumination for dramatic edge-to-edge glow effects.',
    category: 'cast-block-acrylic',
    image: '/images/hero-lp11-s.jpg',
    gallery: [
      '/images/hero-lp11-s.jpg',
      '/images/products/lp11-s-day.jpg',
      '/images/products/lp11-s-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: '30mm (1.2") cast block acrylic' },
      { label: 'Illumination', value: 'Full side-lit' },
      { label: 'Sealing', value: 'Epoxy-sealed IP67 waterproof' },
      { label: 'Customization', value: 'PMS colors, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Stroke Width', value: '12mm (0.47")' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'No maintenance required' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Nightlife and entertainment venues',
      'Modern retail environments',
      'Eye-catching facade signage',
      'Distinctive brand installations',
    ],
    features: [
      'Full side-lit illumination',
      '30mm cast block acrylic construction',
      'IP67 waterproof epoxy sealed',
      'Dramatic edge-to-edge glow',
      'No maintenance required',
      'PMS color matching available',
    ],
    relatedSlugs: ['edgeluxe-lp11-bs', 'edgeluxe-lp11-fs', 'edgeluxe-lp11-n'],
  },
  {
    slug: 'edgeluxe-lp11-n',
    name: 'Faux Neon',
    modelNumber: 'EdgeLuxe LP11-N',
    tagline: 'Authentic neon appearance without the fragility.',
    description: '30mm cast block acrylic routed to simulate neon glass tube with embedded LEDs for authentic neon appearance without the fragility. All the charm of traditional neon with the durability and efficiency of modern LED technology.',
    shortDescription: '30mm cast block acrylic routed to simulate neon glass tube with embedded LEDs for authentic neon appearance.',
    category: 'cast-block-acrylic',
    image: '/images/hero-lp11-n.jpg',
    gallery: [
      '/images/hero-lp11-n.jpg',
      '/images/products/lp11-n-day.jpg',
      '/images/products/lp11-n-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: '30mm (1.2") cast block acrylic' },
      { label: 'Illumination', value: 'Faux Neon (routed tube effect)' },
      { label: 'Sealing', value: 'Epoxy-sealed IP67 waterproof' },
      { label: 'Customization', value: 'PMS colors, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Stroke Width', value: '12mm (0.47")' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'No maintenance required' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Bars and restaurants',
      'Retro and vintage-themed spaces',
      'Entertainment venues',
      'Creative brand installations',
    ],
    features: [
      'Faux neon glass tube effect',
      '30mm cast block acrylic construction',
      'IP67 waterproof epoxy sealed',
      'Authentic neon look, LED durability',
      'No maintenance required',
      'PMS color matching available',
    ],
    relatedSlugs: ['edgeluxe-lp11-s', 'edgeluxe-lp11-f', 'edgeluxe-lp11-c'],
  },
  {
    slug: 'edgeluxe-lp11-c',
    name: 'Conical Profile Face-Lit',
    modelNumber: 'EdgeLuxe LP11-C',
    tagline: 'Tapered profile for narrow strokes and dimensional detail.',
    description: '30mm cast block acrylic with conical profile for narrow strokes and dimensional letters. Embedded LEDs provide uniform face-lit illumination. Profile tapers from 12mm at back to 3mm on face for a refined, sculpted appearance.',
    shortDescription: '30mm cast block acrylic with conical profile for narrow strokes and dimensional letters.',
    category: 'cast-block-acrylic',
    image: '/images/hero-lp11-c.jpg',
    gallery: [
      '/images/hero-lp11-c.jpg',
      '/images/products/lp11-c-day.jpg',
      '/images/products/lp11-c-night.jpg',
    ],
    specs: [
      { label: 'Materials', value: '30mm (1.2") cast block acrylic' },
      { label: 'Profile', value: 'Conical: 12mm (0.47") back tapering to 3mm (0.12") face' },
      { label: 'Illumination', value: 'Embedded LEDs, uniform face-lit' },
      { label: 'Sealing', value: 'Epoxy-sealed IP67 waterproof' },
      { label: 'Customization', value: 'PMS colors, vinyls, pigmented translucent acrylics' },
      { label: 'Min. Height', value: '50mm (2")' },
      { label: 'Maintenance', value: 'No maintenance required' },
      { label: 'Warranty', value: '3 Years' },
      { label: 'Certification', value: 'UL Listed' },
      { label: 'Production', value: '5\u20137 days' },
    ],
    applications: [
      'Elegant brand signage with fine detail',
      'Luxury retail storefronts',
      'Hospitality and resort signage',
      'Architectural installations requiring precision',
    ],
    features: [
      'Conical profile for narrow strokes',
      '30mm cast block acrylic construction',
      'IP67 waterproof epoxy sealed',
      'Tapered design: 12mm back to 3mm face',
      'No maintenance required',
      'PMS color matching available',
    ],
    relatedSlugs: ['edgeluxe-lp11-f', 'edgeluxe-lp11-n', 'edgeluxe-lp11-fb'],
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getRelatedProducts(product: Product): Product[] {
  return product.relatedSlugs
    .map((slug) => getProductBySlug(slug))
    .filter((p): p is Product => p !== undefined)
}

export function getProductsByCategory(category: Product['category']): Product[] {
  return products.filter((p) => p.category === category)
}

export const categories = [
  { id: 'all' as const, label: 'All Products' },
  { id: 'fabricated-channel-letters' as const, label: 'Fabricated Channel Letters' },
  { id: 'cast-block-acrylic' as const, label: 'Cast Block Acrylic' },
]
